### PR TITLE
Allow sending nested params.

### PR DESCRIPTION
**Pull request by SeregPie**
Closes the issue #4.

### CODE REVIEW

**Comment by setyongr** [comment]
Hi, thanks for PR
Can you add typescript definition for `qs` package?
It should be `@types/qs`

**Comment by SeregPie** [comment]
sorry. i'm absolutely not familiar with typescript.

**Comment by setyongr** [comment]
Okay, no problem
Thanks

**Comment by setyongr** [comment]
Oh crap, i accidentally click close before merging, and cannot reopen it, can you resubmit it?

**Pull request closed without merging**
